version: "3.10"
services:
  app:
    build: .
    volumes:
      - .:/crowdsourcing-platform
    ports:
      - 8000:8000
    image: app:crowdsourcing-platform
    container_name: crowdsourcing_container
    command: python manage.py runserver  0.0.0.0:8000
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_db