version: "3.10"
services:

# REDIS
  redis:
    image: redis:latest
    container_name: redis
    restart: always

  # POSTGRESQL DB
  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    # networks:
    #   app_net:
    #     ipv4_address: 192.168.0.2

  app:
    build: .
    restart: always
    volumes:
      - .:/crowdsourcing-platform
    ports:
      - 8000:8000
    image: app:crowdsourcing-platform
    container_name: crowdsourcing_container
    command: python manage.py runserver  0.0.0.0:8000
    depends_on:
      - db


  # CELERY
  celery:
    restart: always
    build:
      context: .
    command: celery -A crowdsourcing worker -l INFO
    volumes:
      - .:/crowdsourcing-platform
    container_name: celery
    depends_on:
      - db
      - rabbit
      - redis
      - app

  rabbit:
    image: rabbitmq:3-management
    restart: always
    env_file:
      - .env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    container_name: rabbit
    hostname: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
  pgadmin:
    container_name: pgadmin4
    env_file:
      - .env
    volumes:
      - ./data/pgadmin-data:/var/lib/pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT}
    ports:
      - "5050:80"
    # networks:
    #   app_net:
    #     ipv4_address: 192.168.0.3

# networks:
#   app_net:
#     ipam: 
#       driver: default
#       config: 
#         - subnet: "192.168.0.0/24"
#           gateway: 192.168.0.1