version: "3.10"
services:
  app:
    build: .
    volumes:
      - .:/crowdsourcing-platform
    ports:
      - 8000:8000
    image: app:crowdsourcing-platform
    container_name: crowdsourcing_container
    command: python manage.py runserver  0.0.0.0:8000