version: "3.10"
services:

# REDIS
  redis:
    image: redis:latest
    container_name: redis

  # POSTGRESQL DB
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_db

  app:
    build: .
    volumes:
      - .:/crowdsourcing-platform
    ports:
      - 8000:8000
    image: app:crowdsourcing-platform
    container_name: crowdsourcing_container
    command: python manage.py runserver  0.0.0.0:8000
    depends_on:
      - db


  # CELERY
  celery:
    restart: always
    build:
      context: .
    command: celery -A crowdsourcing worker -l INFO
    volumes:
      - .:/crowdsourcing-platform
    container_name: celery
    depends_on:
      - db
      - rabbit
      - redis
      - app

  rabbit:
    image: rabbitmq:3-management
    env_file:
      - .env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    container_name: rabbit
    hostname: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"