# Generated by Django 4.2.2 on 2023-09-13 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_baseuser_about_me'),
        ('core', '0002_project_innovator_user_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='certified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.moderator'),
        ),
    ]
