# Generated by Django 4.2.2 on 2023-09-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_certified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='business_type',
            field=models.CharField(choices=[('REAL ESTATE', 'Real Estate'), ('TRANSPORTATION', 'Transportation'), ('FORESTRY', 'Forestry'), ('AGRICULTURE', 'Agriculture'), ('CONSTRUCTION', 'Construction'), ('ENERGY', 'Energy'), ('TECHNOLOGY', 'Technology'), ('HEALTHCARE', 'Healthcare'), ('CONSUMER GOODS', 'Consumer Goods'), ('FINANCE AND BANKING', 'Finance and Banking'), ('HOSPITALITY AND TOURISM', 'Hospitality and Tourism'), ('ENTERTAINMENT AND MEDIA', 'Entertainment and Media'), ('MANUFACTURING', 'Manufacturing'), ('MINING AND NATURAL RESOURCES', 'Mining and Natural Resources'), ('ENVIRONMENTAL AND SUSTAINABILITY', 'Environmental and Sustainability'), ('EDUCATION AND EDTECH', 'Education and Edtech')], default='REAL ESTATE', max_length=255),
        ),
    ]
