# Generated by Django 4.2.2 on 2023-09-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_project_business_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='business_type',
            field=models.CharField(max_length=255),
        ),
    ]
