# Generated by Django 4.2.2 on 2023-09-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_project_business_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='fund_raised',
            field=models.DecimalField(decimal_places=2, max_digits=255, null=True),
        ),
    ]
