# Generated by Django 4.2.2 on 2023-09-13 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_baseuser_about_me'),
        ('core', '0007_alter_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='certified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.moderator'),
        ),
        migrations.AlterField(
            model_name='project',
            name='fund_raised',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=255, null=True),
        ),
    ]
