# Generated by Django 4.2.2 on 2023-09-13 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_project_certified_by_alter_project_fund_raised'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='date_created',
        ),
    ]
