# Generated by Django 4.2.4 on 2023-09-16 09:38

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_rename_innovator_service_user'),
        ('core', '0012_contribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Innovation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True, max_length=10000, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to=core.models.upload_project_gallery)),
                ('status', models.BooleanField(default='Unapproved')),
                ('category', models.CharField(max_length=255)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('num_of_contributions', models.IntegerField(blank=True, default=0, null=True)),
                ('reward', models.DecimalField(decimal_places=2, max_digits=255)),
                ('views', models.IntegerField(default=0)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.moderator')),
                ('contribution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.contribution')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.innovator')),
            ],
        ),
    ]
