# Generated by Django 4.2.4 on 2023-09-16 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_rename_innovator_service_user'),
        ('core', '0013_innovation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_name', to='accounts.moderator'),
        ),
    ]
