# Generated by Django 4.2.4 on 2023-09-16 10:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_contribution_innovation_contributions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovation',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
