# Generated by Django 4.2.4 on 2023-09-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_innovation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovation',
            name='status',
            field=models.CharField(default='Unapproved', max_length=255),
        ),
    ]
