# Generated by Django 4.2.4 on 2023-09-16 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_rename_innovator_service_user'),
        ('core', '0018_alter_innovation_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='innovation',
            unique_together={('title', 'owner')},
        ),
    ]
