# Generated by Django 4.2.4 on 2023-09-16 12:55

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_innovation_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_innovation_images),
        ),
    ]
