# Generated by Django 4.2.4 on 2023-09-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_innovation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovation',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
