# Generated by Django 4.2.4 on 2023-09-16 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_contribution_contribution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='contributor',
        ),
        migrations.RemoveField(
            model_name='innovation',
            name='contributions',
        ),
        migrations.AddField(
            model_name='contribution',
            name='innovation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.innovation'),
        ),
    ]
