# Generated by Django 4.2.4 on 2023-09-16 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_rename_innovator_service_user'),
        ('core', '0023_remove_contribution_contributor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='contributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.innovator'),
        ),
    ]
