# Generated by Django 4.2.4 on 2023-09-16 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_nested_contribution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nested_contribution',
            old_name='contribution',
            new_name='nested_contribution',
        ),
    ]
