# Generated by Django 4.2.4 on 2023-09-17 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_rename_contribution_nested_contribution_nested_contribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_contrib', to='core.contribution'),
        ),
        migrations.DeleteModel(
            name='Nested_Contribution',
        ),
    ]
