# Generated by Django 4.2.4 on 2023-09-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_rename_innovator_service_user'),
        ('core', '0027_contribution_parent_delete_nested_contribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='downvoted_by',
            field=models.ManyToManyField(blank=True, related_name='downvoted_contributions', to='accounts.innovator'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='upvoted_by',
            field=models.ManyToManyField(blank=True, related_name='upvoted_contributions', to='accounts.innovator'),
        ),
    ]
