# Generated by Django 4.2.4 on 2023-09-19 14:17

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_reward_payment_investment_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment_payment',
            name='expected_return',
            field=core.models.ExpectedReturnField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
