# Generated by Django 4.2.4 on 2023-09-19 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_investment_payment_expected_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment_payment',
            name='investment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='the_investment', to='core.project'),
        ),
    ]
