# Generated by Django 4.2.4 on 2023-09-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_investment_payment_investment'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment_payment',
            name='date_sent',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='reward_payment',
            name='date_sent',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
