# Generated by Django 4.2.4 on 2023-09-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_investment_payment_date_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment_payment',
            name='status',
            field=models.CharField(default='YET TO BE REVIEWED', max_length=255, null=True),
        ),
    ]
