# Generated by Django 4.2.4 on 2023-09-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_investment_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment_payment',
            name='status',
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(default='YET TO BE REVIEWED', max_length=255, null=True),
        ),
    ]
