# Generated by Django 4.2.4 on 2023-09-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_project_amount_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='amount_left',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='fund_raised',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=255, null=True),
        ),
    ]
