# Generated by Django 4.2.4 on 2023-09-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_project_amount_left_alter_project_fund_raised'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='downvotes',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='upvotes',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='innovation',
            name='downvotes',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='innovation',
            name='num_of_contributions',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='innovation',
            name='upvotes',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='innovation',
            name='views',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='investment_payment',
            name='amount',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='project',
            name='amount_left',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='fund_raised',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=255, null=True),
        ),
        migrations.AlterField(
            model_name='reward_payment',
            name='amount',
            field=models.IntegerField(default='0'),
        ),
    ]
