# Generated by Django 4.2.4 on 2023-09-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_contribution_downvotes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='downvotes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='upvotes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='innovation',
            name='downvotes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='innovation',
            name='num_of_contributions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='innovation',
            name='upvotes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='innovation',
            name='views',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='investment_payment',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='amount_left',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='fund_raised',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=255, null=True),
        ),
        migrations.AlterField(
            model_name='reward_payment',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
