# Generated by Django 4.2.4 on 2023-09-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_contribution_downvotes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
