# Generated by Django 4.2.4 on 2023-09-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_contribution_downvotes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='downvotes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='upvotes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
