# Generated by Django 4.2.4 on 2023-09-30 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_baseuser_is_innovator_baseuser_is_moderator'),
        ('core', '0044_alter_contribution_downvotes_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Investment_Payment',
            new_name='Make_Investment',
        ),
    ]
