# Generated by Django 4.2.4 on 2023-10-03 20:39

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_baseuser_is_innovator_baseuser_is_moderator'),
        ('core', '0045_rename_investment_payment_make_investment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='make_investment',
            name='expected_return',
            field=models.DecimalField(decimal_places=2, max_digits=255, null=True),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('date_generated', models.DateTimeField(auto_now_add=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_owner', to='accounts.innovator')),
            ],
        ),
    ]
