# Generated by Django 4.2.4 on 2023-10-03 21:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_make_investment_expected_return_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='amount',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='reference_code',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='successful',
            field=models.BooleanField(default=False),
        ),
    ]
