# Generated by Django 4.2.4 on 2023-10-03 21:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_receipt_amount_receipt_reference_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='amount',
            field=models.PositiveIntegerField(blank=True, default=uuid.uuid5, editable=False, null=True),
        ),
    ]
