# Generated by Django 4.2.4 on 2023-10-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alter_receipt_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='description',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
