# Generated by Django 4.2.4 on 2023-10-03 23:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_alter_receipt_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='make_investment',
            name='reference_code',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
