# Generated by Django 4.2.4 on 2023-10-07 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_transaction_delete_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
    ]
