# Generated by Django 4.2.4 on 2023-10-07 19:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_alter_baseuser_website'),
        ('core', '0057_alter_transaction_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('reference_code', models.UUIDField(default=uuid.uuid5, null=True)),
                ('account_number', models.IntegerField(blank=True)),
                ('bank', models.CharField(max_length=254)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('innovator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.innovator')),
            ],
        ),
    ]
