# Generated by Django 4.2.4 on 2023-10-07 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_alter_baseuser_website'),
        ('core', '0058_withdraw'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Withdraw',
            new_name='Withdrawal',
        ),
    ]
