# Generated by Django 4.2.4 on 2023-10-07 23:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_rename_withdraw_withdrawal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='reference_code',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
