# Generated by Django 4.2.4 on 2023-10-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_alter_withdrawal_reference_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdrawal',
            old_name='bank',
            new_name='bank_name',
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='bank_code',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
