# Generated by Django 4.2.4 on 2023-10-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_rename_bank_withdrawal_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='account_holder',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
