# Generated by Django 4.2.4 on 2023-10-08 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_withdrawal_account_holder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='account_number',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
