# Generated by Django 4.2.4 on 2023-10-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_alter_withdrawal_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositmoney',
            name='pre_balance',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='pre_balance',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
