# Generated by Django 4.2.4 on 2023-10-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_depositmoney_pre_balance_withdrawal_pre_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositmoney',
            name='post_balance',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='post_balance',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
