# Generated by Django 4.2.4 on 2023-10-11 16:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_alter_baseuser_website'),
        ('core', '0065_depositmoney_post_balance_withdrawal_post_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('reference_code', models.UUIDField(default=uuid.uuid4, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('pre_balance', models.PositiveIntegerField(blank=True, null=True)),
                ('post_balance', models.PositiveIntegerField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_recipient', to='accounts.innovator')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_sender', to='accounts.innovator')),
            ],
        ),
    ]
