# Generated by Django 4.2.4 on 2023-10-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_transaction_post_balance_transaction_pre_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
