# Generated by Django 4.2.4 on 2023-10-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_projectfund_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalfund',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='projectfund',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
