# Generated by Django 4.2.4 on 2023-10-17 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_remove_innovator_owner_funds_and_more'),
        ('core', '0071_personalfund_last_updated_projectfund_last_updated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonalFund',
        ),
    ]
