# Generated by Django 4.2.4 on 2023-10-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_withdrawprojectfunds'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='withdrawprojectfunds',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
