# Generated by Django 4.2.4 on 2023-10-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_withdrawal_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='confirmation',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='withdrawprojectfunds',
            name='confirmation',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
