# Generated by Django 4.2.4 on 2023-10-31 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_withdrawal_confirmation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='confirmation_clicked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='withdrawprojectfunds',
            name='confirmation_clicked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
