# Generated by Django 4.2.4 on 2023-11-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_withdrawal_confirmation_clicked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='kbq_answer',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='withdrawprojectfunds',
            name='kbq_answer',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
