# Generated by Django 4.2.4 on 2023-11-02 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_alter_kbaquestion_kba_question'),
        ('core', '0079_withdrawal_kbq_answer_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.moderator'),
        ),
        migrations.AddField(
            model_name='withdrawprojectfunds',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.moderator'),
        ),
    ]
