# Generated by Django 4.2.4 on 2023-11-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_withdrawal_withdrawal_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='date_approved',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawprojectfunds',
            name='date_approved',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
