# Generated by Django 4.2.4 on 2023-11-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_withdrawal_date_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmoney',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
