# Generated by Django 4.2.4 on 2023-11-08 05:02

import ckeditor.fields
import core.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_sendmoney_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, max_length=10000, null=True)),
                ('target_date', models.DateField()),
                ('progress_report', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to=core.models.upload_project_milestone_gallery)),
                ('image_2', models.ImageField(blank=True, null=True, upload_to=core.models.upload_project_milestone_gallery)),
                ('image_3', models.ImageField(blank=True, null=True, upload_to=core.models.upload_project_milestone_gallery)),
                ('video', models.FileField(null=True, upload_to=core.models.upload_project_milestone_gallery, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
        ),
    ]
