# Generated by Django 4.2.4 on 2023-11-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_projectmilestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmilestone',
            name='status',
            field=models.CharField(blank=True, choices=[('DELAYED', 'Delayed'), ('IN PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], max_length=254, null=True),
        ),
    ]
