# Generated by Django 4.2.4 on 2023-11-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_projectmilestone_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmilestone',
            name='status',
            field=models.CharField(choices=[('DELAYED', 'Delayed'), ('IN PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], max_length=254, null=True),
        ),
    ]
