# Generated by Django 4.2.4 on 2023-11-08 11:37

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_alter_projectmilestone_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmilestone',
            name='image_1',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to=core.models.upload_project_milestone_gallery),
        ),
        migrations.AlterField(
            model_name='projectmilestone',
            name='image_2',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to=core.models.upload_project_milestone_gallery),
        ),
        migrations.AlterField(
            model_name='projectmilestone',
            name='image_3',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to=core.models.upload_project_milestone_gallery),
        ),
        migrations.AlterField(
            model_name='projectmilestone',
            name='video',
            field=models.FileField(max_length=254, null=True, upload_to=core.models.upload_project_milestone_gallery, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
