# Generated by Django 4.2.4 on 2023-11-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_alter_projectmilestone_image_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmilestone',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
