# Generated by Django 4.2.4 on 2023-11-09 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_alter_kbaquestion_kba_question'),
        ('core', '0089_alter_projectmilestone_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='make_investment',
            name='send_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='accounts.innovator'),
        ),
        migrations.AlterField(
            model_name='make_investment',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor', to='accounts.innovator'),
        ),
    ]
