# Generated by Django 4.2.4 on 2023-12-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_alter_project_fund_raised'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
