# Generated by Django 4.2.4 on 2023-12-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_contribution_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovation',
            name='reward_paid',
            field=models.BooleanField(default=False),
        ),
    ]
