# Generated by Django 4.2.4 on 2024-01-03 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_testimony'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimony',
            old_name='content',
            new_name='review',
        ),
    ]
