# Generated by Django 4.2.4 on 2024-01-03 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_rename_content_testimony_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimony',
        ),
    ]
