# Generated by Django 4.2.4 on 2024-01-03 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_testimony'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimony',
        ),
    ]
