# Generated by Django 4.2.4 on 2024-01-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_alter_project_business_type_alter_project_image_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='fund_raised',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=255),
        ),
    ]
