# Generated by Django 4.2.4 on 2024-01-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_alter_project_fund_raised'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='innovation',
            name='reward_paid',
        ),
        migrations.AlterField(
            model_name='innovation',
            name='reward',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=255, null=True),
        ),
    ]
