# Generated by Django 4.2.4 on 2024-01-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_remove_innovation_reward_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovation',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='innovation',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
