# Generated by Django 4.2.4 on 2024-01-10 14:43

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_alter_innovation_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovation',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=core.models.upload_innovation_images),
        ),
    ]
