# Generated by Django 4.2.4 on 2024-01-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_alter_innovation_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
