# Generated by Django 4.2.4 on 2024-01-12 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_alter_contribution_downvotes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmilestone',
            name='target_date',
        ),
    ]
