# Generated by Django 4.2.4 on 2024-01-14 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0075_rename_downvote_testimony_downvotes_and_more'),
        ('core', '0108_remove_projectmilestone_target_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='certified_by',
        ),
        migrations.AddField(
            model_name='project',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.moderator'),
        ),
    ]
