# Generated by Django 4.2.4 on 2024-01-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_project_target_reached'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(default='YET TO BE REVIEWED', max_length=255),
        ),
    ]
