# Generated by Django 4.2.4 on 2023-12-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_chat_id_chat_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='chat_id',
        ),
        migrations.AddField(
            model_name='chat',
            name='id',
            field=models.BigAutoField(auto_created=True, default=12, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
