# Generated by Django 4.2.4 on 2023-12-12 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_chat_chat_id_chat_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ('timestamp',)},
        ),
        migrations.AlterModelOptions(
            name='groupchat',
            options={'ordering': ('timestamp',)},
        ),
        migrations.AddField(
            model_name='groupchat',
            name='message_tagged',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_to', to='chat.groupchat'),
        ),
    ]
