# Generated by Django 4.2.4 on 2023-12-12 15:45

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chat_options_alter_groupchat_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='file_content',
            field=models.FileField(blank=True, null=True, upload_to=chat.models.upload_group_inchat_files),
        ),
    ]
