# Generated by Django 4.2.4 on 2024-01-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
