# Generated by Django 4.2.4 on 2023-11-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chat_recipient_alter_chat_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
