# Generated by Django 4.2.4 on 2023-12-02 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_alter_make_investment_send_to_and_more'),
        ('chat', '0009_chat_file_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='investment_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.project'),
        ),
    ]
