# Generated by Django 4.2.4 on 2023-12-04 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_group_investment_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='is_seen',
        ),
    ]
