# Generated by Django 4.2.4 on 2023-12-07 09:00

import chat.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0011_remove_chat_is_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('file_content', models.FileField(blank=True, null=True, upload_to=chat.models.upload_in_chat_files)),
                ('message_tagged', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_tagged', to='chat.chat')),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_chat_recipient', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_chat_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
