# Generated by Django 4.1.6 on 2023-02-06 15:40

import accounts.models
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_name", models.CharField(max_length=256)),
                ("first_name", models.CharField(max_length=256)),
                ("middle_name", models.CharField(max_length=256)),
                ("username", models.CharField(max_length=256, unique=True)),
                ("email", models.EmailField(max_length=128, unique=True)),
                (
                    "pfp",
                    models.ImageField(upload_to=accounts.models.upload_location_pfp),
                ),
                (
                    "id_card",
                    models.ImageField(
                        upload_to=accounts.models.upload_location_id_card
                    ),
                ),
                ("city", models.CharField(max_length=128)),
                ("state", models.CharField(max_length=128)),
                ("country", models.CharField(max_length=128)),
                ("address", models.CharField(max_length=128)),
                (
                    "phone_num",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        region=None,
                        verbose_name="Phone Number",
                    ),
                ),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("last_login", models.DateTimeField(auto_now=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("VENDOR", "Vendor"),
                            ("INNOVATOR", "Innovator"),
                            ("INVESTOR", "Investor"),
                        ],
                        default="INNOVATOR",
                        max_length=50,
                        verbose_name="Type",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Innovator",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounts.user",),
        ),
        migrations.CreateModel(
            name="Investor",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounts.user",),
        ),
        migrations.CreateModel(
            name="Moderator",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounts.user",),
        ),
    ]
