# Generated by Django 4.1.6 on 2023-02-06 17:31

import accounts.models
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="id_card",
            field=models.ImageField(
                null=True, upload_to=accounts.models.upload_location_id_card
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="pfp",
            field=models.ImageField(
                null=True, upload_to=accounts.models.upload_location_pfp
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_num",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region=None,
                verbose_name="Phone Number",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="state",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
