# Generated by Django 4.2.4 on 2023-08-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovator',
            name='downvotes_received',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='innovator',
            name='innovations_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='innovator',
            name='is_project_mgr',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='innovator',
            name='upvotes_received',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
