# Generated by Django 4.2.3 on 2023-07-23 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_contributor_setup_by_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderator',
            name='setup_by_admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='setup_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
