# Generated by Django 4.2.3 on 2023-07-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='type',
            field=models.CharField(choices=[('CONTRIBUTOR', 'Contributor'), ('REVIEWER', 'Reviewer'), ('INVESTOR', 'Investor'), ('PROJECT MANAGER', 'Project Manager'), ('ADMINISTRATOR', 'Administrator')], default='CONTRIBUTOR', max_length=50, verbose_name='Type'),
        ),
    ]
