# Generated by Django 4.1.6 on 2023-02-07 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_address_alter_user_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="signup_confirmation",
            field=models.BooleanField(default=False),
        ),
    ]
