# Generated by Django 4.2.3 on 2023-07-23 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_moderator_setup_by_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderator',
            name='setup_by_admin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setup_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
