# Generated by Django 4.2.3 on 2023-07-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_moderator_setup_by_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='genmodsignuplink',
            name='random_string',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
