# Generated by Django 4.2.4 on 2023-08-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovator',
            name='service_1',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='innovator',
            name='service_2',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='innovator',
            name='service_3',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='innovator',
            name='service_4',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='innovator',
            name='service_5',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
