# Generated by Django 4.2.3 on 2023-07-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_baseuser_moderator_delete_userprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
