# Generated by Django 4.2.3 on 2023-07-23 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_moderator_user_delete_genmodsignuplink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
