# Generated by Django 4.2.2 on 2023-07-25 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_moderator_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='remember_me',
        ),
    ]
