# Generated by Django 4.2.2 on 2023-07-27 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_contributor_is_investor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderator',
            name='setup_by_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setup_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
