# Generated by Django 4.2.4 on 2023-09-07 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_baseuser_zipcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='InnovatorSkills',
            fields=[
                ('skill_id', models.IntegerField(primary_key=True, serialize=False)),
                ('skill', models.CharField(blank=True, max_length=255, null=True)),
                ('skill_value', models.IntegerField()),
                ('innovator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.innovator')),
            ],
        ),
    ]
