# Generated by Django 4.2.2 on 2023-07-30 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0010_alter_moderator_setup_by_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Innovator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innovations_count', models.IntegerField(default=0)),
                ('upvotes_received', models.IntegerField(default=0)),
                ('downvotes_received', models.IntegerField(default=0)),
                ('reputation_score', models.IntegerField(default=0)),
                ('is_project_mgr', models.BooleanField(default=False)),
                ('is_investor', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='baseuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.DeleteModel(
            name='Contributor',
        ),
        migrations.AddField(
            model_name='innovator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
