# Generated by Django 4.2.3 on 2023-07-22 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_baseuser_first_name_alter_baseuser_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenModSignUpLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_email', models.EmailField(max_length=254)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
