# Generated by Django 4.2.2 on 2023-07-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_innovator_baseuser_groups_baseuser_user_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='linkedin',
            field=models.URLField(default='https://linkedin.com/'),
        ),
    ]
