# Generated by Django 4.2.4 on 2023-09-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_innovatorskills_innovatorskill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovatorskill',
            name='skill_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
