# Generated by Django 4.2.3 on 2023-07-30 23:36

from django.db import migrations
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_baseuser_linkedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='country',
            field=django_countries.fields.CountryField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='phone_num',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True, verbose_name='Phone Number'),
        ),
    ]
