# Generated by Django 4.2.4 on 2023-09-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_innovatorskill_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='signup_with_google',
            field=models.BooleanField(default=False),
        ),
    ]
