# Generated by Django 4.2.3 on 2023-07-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_baseuser_bio_alter_baseuser_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='zipcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
