# Generated by Django 4.2.4 on 2023-09-08 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_baseuser_signup_with_google'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='skill_1',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='skill_10',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='skill_2',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='skill_3',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='skill_4',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='skill_5',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='skill_6',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='skill_7',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='skill_8',
        ),
        migrations.RemoveField(
            model_name='baseuser',
            name='skill_9',
        ),
    ]
