# Generated by Django 4.2.4 on 2023-09-09 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_baseuser_skill_1_remove_baseuser_skill_10_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('innovator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.innovator')),
            ],
        ),
    ]
