# Generated by Django 4.2.3 on 2023-08-01 08:10

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_baseuser_pfp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='id_card',
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='pfp',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.upload_location_pfp),
        ),
    ]
