# Generated by Django 4.2.4 on 2023-09-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_innovator_about_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovator',
            name='about_me',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
