# Generated by Django 4.2.4 on 2023-09-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_remove_innovator_service_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='innovator',
            name='about_me',
        ),
        migrations.AddField(
            model_name='baseuser',
            name='about_me',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
