# Generated by Django 4.2.4 on 2023-09-18 06:43

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='pfp',
            field=models.ImageField(blank=True, default='/static/accounts/images/default_profile_image.jpg', null=True, upload_to=accounts.models.upload_location_pfp),
        ),
    ]
