# Generated by Django 4.2.3 on 2023-08-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_skill_baseuser_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='skills',
        ),
        migrations.AddField(
            model_name='baseuser',
            name='skill_1',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='skill_10',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='skill_2',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='skill_3',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='skill_4',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='skill_5',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='skill_6',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='skill_7',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='skill_8',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='skill_9',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
