# Generated by Django 4.2.4 on 2023-09-19 14:04

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_baseuser_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='pfp',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.upload_location_pfp),
        ),
    ]
