# Generated by Django 4.2.4 on 2023-09-20 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_baseuser_pfp'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovator',
            name='account_balance',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='LoadMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, null=True)),
                ('innovator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.innovator')),
            ],
        ),
    ]
