# Generated by Django 4.2.4 on 2023-08-08 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_remove_baseuser_skills_baseuser_skill_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_1', models.CharField(max_length=254, null=True)),
                ('service_2', models.CharField(max_length=254, null=True)),
                ('service_3', models.CharField(max_length=254, null=True)),
                ('service_4', models.CharField(max_length=254, null=True)),
                ('service_5', models.CharField(max_length=254, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='baseuser',
            name='services',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.services'),
        ),
    ]
