# Generated by Django 4.2.4 on 2023-09-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_innovator_account_balance_loadmoney'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='is_innovator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='is_moderator',
            field=models.BooleanField(default=False),
        ),
    ]
