# Generated by Django 4.2.4 on 2023-10-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_baseuser_is_innovator_baseuser_is_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
