# Generated by Django 4.2.4 on 2023-08-08 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_service_alter_baseuser_services_delete_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='services',
        ),
        migrations.AddField(
            model_name='innovator',
            name='services',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.service'),
        ),
    ]
