# Generated by Django 4.2.4 on 2023-10-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_delete_loadmoney'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='website',
            field=models.URLField(blank=True, default='https://company.com/', null=True),
        ),
    ]
