# Generated by Django 4.2.4 on 2023-10-17 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_projectfund_personalfund'),
        ('accounts', '0035_remove_innovator_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovator',
            name='owner_funds',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.personalfund'),
        ),
    ]
