# Generated by Django 4.2.4 on 2023-10-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_remove_innovator_owner_funds_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='innovator',
            name='personal_funds',
        ),
        migrations.AddField(
            model_name='innovator',
            name='account_balance',
            field=models.IntegerField(null=True),
        ),
    ]
