# Generated by Django 4.2.4 on 2023-10-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_remove_innovator_personal_funds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='nin',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
