# Generated by Django 4.2.4 on 2023-10-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_baseuser_nin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='nin',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
