# Generated by Django 4.2.4 on 2023-10-27 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_kbaquestion_baseuser_kba'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='kba',
        ),
        migrations.AddField(
            model_name='kbaquestion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kbaquestion',
            name='answer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='kbaquestion',
            name='kba_question',
            field=models.CharField(blank=True, choices=[('book', 'What is the name of your favorite childhood book?'), ('city', 'In which city were you born?'), ('pet', 'What is the name of your first pet?'), ('hero', 'Who was your childhood hero?'), ('movie', 'What is your favorite childhood movie?'), ('maiden', "What is your mother's maiden name?"), ('stuffed-animal', 'What was the name of your first stuffed animal?'), ('favorite-teacher', 'What is the name of your favorite teacher from elementary school?'), ('vacation-spot', 'What was your favorite childhood vacation spot?'), ('best-friend', 'What is the name of your first best friend?')], max_length=254, null=True),
        ),
    ]
