# Generated by Django 4.2.4 on 2023-11-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_remove_baseuser_kba_kbaquestion_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kbaquestion',
            name='kba_question',
            field=models.CharField(blank=True, choices=[('What is the name of your favorite childhood book?', 'What is the name of your favorite childhood book?'), ('In which city were you born?', 'In which city were you born?'), ('What is the name of your first pet?', 'What is the name of your first pet?'), ('Who was your childhood hero?', 'Who was your childhood hero?'), ('What is your favorite childhood movie?', 'What is your favorite childhood movie?'), ("What is your mother's maiden name?", "What is your mother's maiden name?"), ('What was the name of your first stuffed animal?', 'What was the name of your first stuffed animal?'), ('What is the name of your favorite teacher from elementary school?', 'What is the name of your favorite teacher from elementary school?'), ('What was your favorite childhood vacation spot?', 'What was your favorite childhood vacation spot?'), ('What is the name of your first best friend?', 'What is the name of your first best friend?')], max_length=254, null=True),
        ),
    ]
