# Generated by Django 4.2.4 on 2023-11-17 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_connectionrequest_remote_response'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connectionrequest',
            old_name='date_sent',
            new_name='date_requested',
        ),
    ]
