# Generated by Django 4.2.4 on 2023-11-17 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='conn_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.connectionrequest'),
        ),
    ]
