# Generated by Django 4.2.4 on 2023-11-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_remove_connectionrequest_date_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionrequest',
            name='date_requested',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
