# Generated by Django 4.2.4 on 2023-11-18 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_connectionrequest_date_requested'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connectionrequest',
            old_name='date_requested',
            new_name='sent_on',
        ),
    ]
