# Generated by Django 4.2.4 on 2023-11-24 20:43

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_rename_date_requested_connectionrequest_sent_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='pfp',
            field=models.ImageField(blank=True, default='pfps/default_profile_image.jpg', null=True, upload_to=accounts.models.upload_location_pfp),
        ),
    ]
