# Generated by Django 4.2.4 on 2023-12-02 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_auto_20231202_1454'),
    ]

    operations = [
    ]
