# Generated by Django 5.0 on 2023-12-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_auto_20231202_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovator',
            name='account_balance',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='innovator',
            name='downvotes_received',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='innovator',
            name='innovations_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='innovator',
            name='is_investor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='innovator',
            name='reputation_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='innovator',
            name='upvotes_received',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
