# Generated by Django 5.0 on 2023-12-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_alter_innovator_account_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
