# Generated by Django 5.0 on 2023-12-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_alter_baseuser_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='middle_name',
            field=models.CharField(blank=True, default='ye', max_length=256, null=True),
        ),
    ]
