# Generated by Django 4.2.4 on 2023-12-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0064_alter_baseuser_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='middle_name',
            field=models.CharField(default='ye', max_length=256),
            preserve_default=False,
        ),
    ]
