# Generated by Django 4.2.4 on 2024-01-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0067_testimony'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
