# Generated by Django 4.2.4 on 2024-01-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0068_alter_testimony_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
