# Generated by Django 4.2.4 on 2024-01-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0071_alter_testimony_dislikes_alter_testimony_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='dislikes',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='testimony',
            name='likes',
            field=models.IntegerField(default='0', null=True),
        ),
    ]
