# Generated by Django 4.2.4 on 2024-01-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0073_alter_testimony_dislikes_alter_testimony_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimony',
            old_name='dislikes',
            new_name='downvote',
        ),
        migrations.RenameField(
            model_name='testimony',
            old_name='likes',
            new_name='upvote',
        ),
        migrations.AddField(
            model_name='testimony',
            name='downvoted_by',
            field=models.ManyToManyField(blank=True, related_name='downvoted_testimonies', to='accounts.innovator'),
        ),
        migrations.AddField(
            model_name='testimony',
            name='upvoted_by',
            field=models.ManyToManyField(blank=True, related_name='upvoted_testimonies', to='accounts.innovator'),
        ),
    ]
