# Generated by Django 4.2.4 on 2024-01-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0075_rename_downvote_testimony_downvotes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovator',
            name='account_balance',
            field=models.IntegerField(default=0),
        ),
    ]
