# Generated by Django 4.2.4 on 2024-01-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0076_alter_innovator_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='about_me',
            field=models.TextField(blank=True, default='', max_length=2000, null=True),
        ),
    ]
